apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-test-deployment
  labels:
    app: load-test
  annotations:
    sidecar.istio.io/inject: "false"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: load-test
  template:
    metadata:
      labels:
        app: load-test
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - name: load-test
          image: hbalik/load-generator:latest
          command:
            - /loadgenerator
          args:
            - -c 2
            - -t telemetry-trace-collector:4317
          imagePullPolicy: Always
          resources:
            requests:
              memory: "128Mi"
            limits:
              memory: "128Mi"